/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#62df7d',
          on: '#003914',
          container: '#1ca64d',
          'on-container': '#003111',
          fixed: '#7ffc97',
          'fixed-dim': '#62df7d',
          'on-fixed': '#002109',
          'on-fixed-variant': '#005320',
        },
        'on-primary': '#003914',
        'primary-container': '#1ca64d',
        'on-primary-container': '#003111',
        'primary-fixed': '#7ffc97',
        'primary-fixed-dim': '#62df7d',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005320',
        'inverse-primary': '#006e2d',
        secondary: {
          DEFAULT: '#bec6e0',
          on: '#283044',
          container: '#3f465c',
          'on-container': '#adb4ce',
          fixed: '#dae2fd',
          'fixed-dim': '#bec6e0',
          'on-fixed': '#131b2e',
          'on-fixed-variant': '#3f465c',
        },
        'on-secondary': '#283044',
        'secondary-container': '#3f465c',
        'on-secondary-container': '#adb4ce',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        tertiary: {
          DEFAULT: '#ffb2bf',
          on: '#660027',
          container: '#ec6284',
          'on-container': '#5a0022',
          fixed: '#ffd9de',
          'fixed-dim': '#ffb2bf',
          'on-fixed': '#3f0016',
          'on-fixed-variant': '#8a143c',
        },
        'on-tertiary': '#660027',
        'tertiary-container': '#ec6284',
        'on-tertiary-container': '#5a0022',
        'tertiary-fixed': '#ffd9de',
        'tertiary-fixed-dim': '#ffb2bf',
        'on-tertiary-fixed': '#3f0016',
        'on-tertiary-fixed-variant': '#8a143c',
        error: {
          DEFAULT: '#ffb4ab',
          on: '#690005',
          container: '#93000a',
          'on-container': '#ffdad6',
        },
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        surface: {
          DEFAULT: '#0e150f',
          on: '#dde5d9',
          variant: '#30372f',
          'on-variant': '#bdcaba',
          dim: '#0e150f',
          bright: '#343b33',
          tint: '#62df7d',
          container: {
            lowest: '#09100a',
            low: '#171d16',
            DEFAULT: '#1b211a',
            high: '#252c24',
            highest: '#30372f',
          },
        },
        'surface-dim': '#0e150f',
        'surface-bright': '#343b33',
        'surface-tint': '#62df7d',
        'surface-variant': '#30372f',
        'surface-container-lowest': '#09100a',
        'surface-container-low': '#171d16',
        'surface-container': '#1b211a',
        'surface-container-high': '#252c24',
        'surface-container-highest': '#30372f',
        'on-surface': '#dde5d9',
        'on-surface-variant': '#bdcaba',
        'inverse-surface': '#dde5d9',
        'inverse-on-surface': '#2b322b',
        background: '#0e150f',
        'on-background': '#dde5d9',
        outline: {
          DEFAULT: '#879485',
          variant: '#3e4a3d',
        },
        'outline-variant': '#3e4a3d',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
      },
      fontFamily: {
        h1: ['Plus Jakarta Sans', 'sans-serif'],
        h2: ['Plus Jakarta Sans', 'sans-serif'],
        h3: ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '0' }],
        h2: ['36px', { lineHeight: '1.2', letterSpacing: '0' }],
        h3: ['24px', { lineHeight: '1.3', letterSpacing: '0' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
