import PDFDocument from 'pdfkit';

const COLORS = {
  primary: '#2d6a4f',
  secondary: '#40916c',
  accent: '#52b788',
  dark: '#1b4332',
  light: '#d8f3dc',
  white: '#ffffff',
  gray: '#6c757d',
  lightGray: '#e9ecef',
  danger: '#dc3545',
  warning: '#ffc107',
  success: '#198754',
  info: '#0dcaf0',
};

const STATUS_COLORS = {
  pending: '#ffc107',
  confirmed: '#0dcaf0',
  dispatched: '#fd7e14',
  delivered: '#198754',
  cancelled: '#dc3545',
};

export const generateOrderReport = async (orders, subOrders, options = {}) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4', layout: 'landscape' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const {
      title = 'KrushiMart Order Report',
      generatedBy = 'Admin',
      dateRange = null,
    } = options;

    // === COVER / HEADER ===
    doc.rect(0, 0, doc.page.width, 90).fill(COLORS.dark);
    doc.fillColor(COLORS.white).fontSize(22).font('Helvetica-Bold').text('KrushiMart', 40, 20, { continued: true }).font('Helvetica').fontSize(14).text('  Order Report', { baseline: 'alphabetic' });
    doc.fontSize(9).fillColor(COLORS.light).text(`Generated by: ${generatedBy}  |  Date: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 40, 55);

    let y = 110;

    // === SUMMARY CARDS ===
    const totalOrders = orders.length;
    const totalRevenue = orders.reduce((sum, o) => sum + (o.totalAmount || 0), 0);
    const statusCounts = {};
    orders.forEach(o => { statusCounts[o.status] = (statusCounts[o.status] || 0) + 1; });

    const cards = [
      { label: 'Total Orders', value: totalOrders, color: COLORS.primary },
      { label: 'Total Revenue', value: `Rs.${totalRevenue.toLocaleString('en-IN')}`, color: COLORS.secondary },
      { label: 'Delivered', value: statusCounts.delivered || 0, color: COLORS.success },
      { label: 'Pending', value: statusCounts.pending || 0, color: COLORS.warning },
      { label: 'Cancelled', value: statusCounts.cancelled || 0, color: COLORS.danger },
    ];

    const cardWidth = (doc.page.width - 80 - (cards.length - 1) * 10) / cards.length;
    cards.forEach((card, i) => {
      const cx = 40 + i * (cardWidth + 10);
      doc.roundedRect(cx, y, cardWidth, 50, 5).fill(card.color);
      doc.fillColor(COLORS.white).fontSize(8).font('Helvetica').text(card.label.toUpperCase(), cx + 10, y + 10, { width: cardWidth - 20 });
      doc.fontSize(16).font('Helvetica-Bold').text(String(card.value), cx + 10, y + 26, { width: cardWidth - 20 });
    });

    y += 70;

    // === ORDERS TABLE HEADER ===
    doc.roundedRect(40, y, doc.page.width - 80, 22, 3).fill(COLORS.dark);
    y += 5;

    const cols = [
      { label: 'Order ID', x: 45, w: 90 },
      { label: 'Date', x: 135, w: 75 },
      { label: 'Customer', x: 210, w: 110 },
      { label: 'Farmer(s)', x: 320, w: 120 },
      { label: 'Items', x: 440, w: 150 },
      { label: 'Status', x: 590, w: 60 },
      { label: 'Amount', x: 650, w: 70 },
    ];

    doc.fillColor(COLORS.white).fontSize(7).font('Helvetica-Bold');
    cols.forEach(col => doc.text(col.label, col.x, y + 3, { width: col.w }));

    y += 22;

    // === ORDER ROWS ===
    orders.forEach((order, idx) => {
      if (y > doc.page.height - 60) {
        doc.addPage();
        y = 40;
        // Re-draw header on new page
        doc.roundedRect(40, y, doc.page.width - 80, 22, 3).fill(COLORS.dark);
        y += 5;
        doc.fillColor(COLORS.white).fontSize(7).font('Helvetica-Bold');
        cols.forEach(col => doc.text(col.label, col.x, y + 3, { width: col.w }));
        y += 22;
      }

      const rowBg = idx % 2 === 0 ? COLORS.white : '#f8f9fa';
      const rowHeight = 28;
      doc.roundedRect(40, y, doc.page.width - 80, rowHeight, 2).fill(rowBg);

      const orderSubOrders = subOrders.filter(so => so.orderId?._id?.toString() === order._id?.toString() || so.orderId?.toString() === order._id?.toString());
      const farmerNames = [...new Set(orderSubOrders.map(so => so.farmerSnapshot?.name || so.farmerId?.name || 'N/A'))].join(', ') || 'N/A';
      const itemNames = order.items?.map(i => i.productId?.name || 'Item').join(', ') || 'N/A';
      const orderDate = order.createdAt ? new Date(order.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'N/A';

      const statusColor = STATUS_COLORS[order.status] || COLORS.gray;

      doc.fontSize(7).font('Helvetica');
      doc.fillColor(COLORS.dark).text(order.orderId || `#${order._id?.slice(-6)}`, cols[0].x, y + 8, { width: cols[0].w });
      doc.fillColor(COLORS.gray).text(orderDate, cols[1].x, y + 8, { width: cols[1].w });
      doc.fillColor(COLORS.dark).text(order.consumerId?.name || 'N/A', cols[2].x, y + 8, { width: cols[2].w });
      doc.fillColor(COLORS.secondary).text(farmerNames, cols[3].x, y + 8, { width: cols[3].w });
      doc.fillColor(COLORS.gray).text(itemNames.length > 30 ? itemNames.substring(0, 28) + '...' : itemNames, cols[4].x, y + 8, { width: cols[4].w });

      // Status badge
      doc.roundedRect(cols[5].x, y + 5, 50, 14, 7).fill(statusColor);
      doc.fillColor(COLORS.white).fontSize(6).font('Helvetica-Bold').text(order.status?.toUpperCase(), cols[5].x, y + 8, { width: 50, align: 'center' });

      doc.fontSize(8).font('Helvetica-Bold').fillColor(COLORS.dark).text(`Rs.${(order.totalAmount || 0).toLocaleString('en-IN')}`, cols[6].x, y + 8, { width: cols[6].w });

      y += rowHeight + 2;
    });

    y += 10;

    // === SUB-ORDER DETAILS ===
    if (y > doc.page.height - 120) {
      doc.addPage();
      y = 40;
    }

    doc.rect(40, y, doc.page.width - 80, 20).fill(COLORS.dark);
    doc.fillColor(COLORS.white).fontSize(10).font('Helvetica-Bold').text('Sub-Order Details (Per Farmer)', 50, y + 5);
    y += 25;

    const subCols = [
      { label: 'Sub-Order ID', x: 45, w: 110 },
      { label: 'Parent Order', x: 155, w: 90 },
      { label: 'Farmer', x: 245, w: 110 },
      { label: 'Consumer', x: 355, w: 110 },
      { label: 'Items', x: 465, w: 140 },
      { label: 'Status', x: 605, w: 60 },
      { label: 'Subtotal', x: 665, w: 70 },
    ];

    doc.roundedRect(40, y, doc.page.width - 80, 20, 3).fill(COLORS.secondary);
    y += 4;
    doc.fillColor(COLORS.white).fontSize(7).font('Helvetica-Bold');
    subCols.forEach(col => doc.text(col.label, col.x, y + 2, { width: col.w }));
    y += 20;

    subOrders.forEach((sub, idx) => {
      if (y > doc.page.height - 50) {
        doc.addPage();
        y = 40;
        doc.roundedRect(40, y, doc.page.width - 80, 20, 3).fill(COLORS.secondary);
        y += 4;
        doc.fillColor(COLORS.white).fontSize(7).font('Helvetica-Bold');
        subCols.forEach(col => doc.text(col.label, col.x, y + 2, { width: col.w }));
        y += 20;
      }

      const rowBg = idx % 2 === 0 ? COLORS.white : '#f8f9fa';
      doc.roundedRect(40, y, doc.page.width - 80, 22, 2).fill(rowBg);

      const subItems = sub.items?.map(i => `${i.productId?.name || 'Item'} x${i.quantity}`).join(', ') || 'N/A';
      const subDate = sub.createdAt ? new Date(sub.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'N/A';
      const statusColor = STATUS_COLORS[sub.status] || COLORS.gray;

      doc.fontSize(6.5).font('Helvetica');
      doc.fillColor(COLORS.dark).text(sub.subOrderId || 'N/A', subCols[0].x, y + 6, { width: subCols[0].w });
      doc.fillColor(COLORS.gray).text(sub.orderId?.orderId || 'N/A', subCols[1].x, y + 6, { width: subCols[1].w });
      doc.fillColor(COLORS.secondary).text(sub.farmerSnapshot?.name || sub.farmerId?.name || 'N/A', subCols[2].x, y + 6, { width: subCols[2].w });
      doc.fillColor(COLORS.dark).text(sub.consumerId?.name || 'N/A', subCols[3].x, y + 6, { width: subCols[3].w });
      doc.fillColor(COLORS.gray).text(subItems.length > 35 ? subItems.substring(0, 33) + '...' : subItems, subCols[4].x, y + 6, { width: subCols[4].w });

      doc.roundedRect(subCols[5].x, y + 3, 48, 12, 6).fill(statusColor);
      doc.fillColor(COLORS.white).fontSize(5.5).font('Helvetica-Bold').text(sub.status?.toUpperCase(), subCols[5].x, y + 6, { width: 48, align: 'center' });

      doc.fontSize(7).font('Helvetica-Bold').fillColor(COLORS.dark).text(`Rs.${(sub.subtotal || 0).toLocaleString('en-IN')}`, subCols[6].x, y + 6, { width: subCols[6].w });

      y += 24;
    });

    // === FOOTER ===
    const pageCount = doc.bufferedPageRange();
    for (let i = 0; i < pageCount.count; i++) {
      doc.switchToPage(pageCount.start + i);
      doc.rect(0, doc.page.height - 30, doc.page.width, 30).fill(COLORS.dark);
      doc.fillColor(COLORS.white).fontSize(7).font('Helvetica')
        .text('KrushiMart - Farm to Table Marketplace', 40, doc.page.height - 20, { width: 300 })
        .text(`Page ${i + 1} of ${pageCount.count}`, doc.page.width - 150, doc.page.height - 20, { width: 110, align: 'right' });
    }

    doc.end();
  });
};
